// Copyright 2016 theaigames.com (developers@theaigames.com)

//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at

//        http://www.apache.org/licenses/LICENSE-2.0

//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
//	
//    For the full copyright and license information, please view the LICENSE
//    file that was distributed with this source code.

package io.riddles.boardgame;

import io.riddles.game.player.AbstractPlayer;


/**
 * abstract class AbstractField
 * 
 * DO NOT EDIT THIS FILE
 * 
 * Extend this class with your main method.
 * 
 * @author Joost de Meij <developers@starapple.nl>
 */
public class AbstractField {
	private AbstractPlayer mOwner;
	private String mType;
	private String mPiece;
	private String mTag;
	
	public AbstractField() {
	}
	
	public void setOwner(AbstractPlayer owner) {
		mOwner = owner;
	}
	public void setType(String type) {
		mType = type;
	}
	public void setPiece(String piece) {
		mPiece = piece;
	}
	public void setTag(String tag) {
		mTag = tag;
	}
	
	public AbstractPlayer getOwner() {
		return mOwner;
	}
	public String getType() {
		return mType;
	}
	public String getPiece() {
		return mPiece;
	}
	public String getTag() {
		return mTag;
	}
	
}
